### ISSUE TITLE
关于 ajax 跨域请求在 IE 上无法发送 cookie 的问题请教

### ISSUE THREAD

**Issue by gongph** [XadillaX/me#3]
您好 @XadillaX :

最近我在做一个注册功能，调用的是后台的一个接口，前台一开始用的是 `axios ` 也设置了 `axios.defaults.withCredentials = true` 。但是请求中没有 `cookie` 导致注册失败。

后来以为是 axios 不兼容 IE 浏览器，然后换成了` jquery` ，也设置了`crossDomain: true, xhrFields: { withCredentials: true} `但还是同样的问题，没法发送 cookie。

最后又换成了 fetch.js 还是不行。前端该设置的都设置了，实在没办法，查了一下，听你在 [node论坛](https://cnodejs.org/topic/58edecb749056f0348347812) 说： `带 cookie 的不能用星号`。

阮一峰也在他的一篇[帖子](http://www.ruanyifeng.com/blog/2016/04/cors.html )中提到过：
`需要注意的是，如果要发送Cookie，Access-Control-Allow-Origin就不能设为星号，必须指定明确的、与请求网页一致的域名`。

我问了下后台 java 人员，他配的是 * 。但是他说没问题。实在找不到问题所在了….
在线等。。。

**Comment by XadillaX** [comment]
他说没问题你就信了？配的 `*` 是可以用的，只不过不能用 Cookie 相关功能，你要 Cookie 功能就不能是 `*`。

**Comment by gongph** [comment]
@XadillaX 我也很无助，跟他沟通半天，他觉得自己很牛X的样子

**Comment by small-tou** [comment]
这个就是沟通的问题了，否则解决不了

**Comment by gongph** [comment]
嗯。多谢！
